version: '2'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox-debug:3.0.1
    ports:
      - "4444:4444"
      - "5900:5900"
  tests:
    image: tests
    build: ./
